In [4]:
import matplotlib.image as mpimage
import matplotlib.pyplot as plt
import numpy as np
import cv2

In [5]:
image=cv2.imread('watchingTV_moving_car.jpg')

In [2]:
cv2.imshow('Watching TV in a car!', image)
k = cv2.waitKey(0)
cv2.destroyAllWindows()

### Print image dimensions

In [3]:
image.shape

(1043, 1600, 3)

In [6]:
gray_image=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow('Show gray image',gray_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Apply sharpenning kernel

In [10]:
# Sharpening Kernel #1
Sharp_Kernel = np.array([[-1,-1,-1], 
                         [-1,9,-1], 
                         [-1,-1,-1]])

sharpened_image=cv2.filter2D(gray_image, -1, Sharp_Kernel)

In [11]:
cv2.imshow('Sharpened Image', sharpened_image)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
### Aggressive sharpenning

As seen in the print screen below some of the edges are to sharp, and this is because of the big difference between central array value of `9` and the `-1`
![IMG]()

In [13]:
Sharp_Kernel = np.array([[0,-1,0], 
                        [-1,5,-1], 
                        [0,-1,0]])
sharpened_image=cv2.filter2D(gray_image, -1, Sharp_Kernel)

In [14]:
cv2.imshow('Sharp image 2', sharpened_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Blur the image

In [16]:
blur_kernel=np.ones((3,3))
blur_kernel

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
blur_image=cv2.filter2D(gray_image, -1, blur_kernel)

In [18]:
cv2.imshow('Blurred image', blur_image)
cv2.waitKey()
cv2.destroyAllWindows()

### The blurring is to aggresive

![IMG]()

This is because the kernel was not normalized. If we pay attention to the other kernels used the sum of the np.array is 1. Whereas here is 9

### Normalize the blur kernel

In [19]:
blur_kernel=np.ones((3,3)) *1/9
blur_kernel

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])

In [21]:
blur_image=cv2.filter2D(gray_image, -1, blur_kernel)

In [23]:
cv2.imshow('Blured_image', blur_image)
cv2.waitKey()
cv2.destroyAllWindows()

### Milder blur img

![IMG]

In [24]:
### Increase the blurring


In [26]:
blur_kernel=np.ones((8,8))
blur_kernel=blur_kernel*1/64
blur_kernel

array([[0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625],
       [0.015625, 0.015625, 0.015625, 0.015625, 0.015625, 0.015625,
        0.015625, 0.015625]])

In [27]:
blur_image=cv2.filter2D(gray_image, -1, blur_kernel)
cv2.waitKey()
cv2.destroyAllWindows()